### ISSUE TITLE
ddclient is quite a good tool for this

### ISSUE THREAD

**Issue by isindir** [kishjogia/DDNS_Updater#1]
Hey @kishjogia,

`ddclient` is quite a good tool for this - supports many dynamic dns providers, it's part of many linux distros:

https://github.com/ddclient/ddclient

there is docker image for it: https://hub.docker.com/r/linuxserver/ddclient

it was once in https://github.com/k8s-at-home/charts/issues/617 (if you add helm repo, it is still installable).

**Comment by kishjogia** [comment]
Awesome thanks.
I have switched to using ddclient, seems to work well
